-- Content store for Studio. One row per editable unit; data is JSON text.
-- Seed rows are generated by scripts/seed-content.mts into 0002_seed.sql.
CREATE TABLE IF NOT EXISTS content (
  id TEXT PRIMARY KEY,
  kind TEXT NOT NULL, -- 'project' | 'copy'
  data TEXT NOT NULL, -- JSON document
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

CREATE INDEX IF NOT EXISTS idx_content_kind ON content (kind);
