import type { WindowDef, WindowId } from '@/desktop/types';

/** Order sets the icon tab order and the window cascade. */
export const WINDOW_ORDER: WindowId[] = [
  'work',
  'reel',
  'about',
  'contact',
  'terminal',
  'games',
  'legal',
];

export const WINDOW_DEFS: Record<WindowId, WindowDef> = {
  work: {
    id: 'work',
    title: 'Work',
    hint: 'Things that shipped',
    icon: '/icons/work.svg',
    defaultSize: { w: 900, h: 600 },
    minSize: { w: 420, h: 360 },
    home: { x: 3, y: 14 },
  },
  reel: {
    id: 'reel',
    title: 'Reel',
    hint: 'Films, cut and coloured',
    icon: '/icons/reel.svg',
    iconScale: 1.16,
    defaultSize: { w: 520, h: 520 },
    minSize: { w: 340, h: 320 },
    home: { x: 3, y: 33 },
  },
  about: {
    id: 'about',
    title: 'About',
    hint: 'Marine engineer who builds software',
    icon: '/icons/about.svg',
    iconScale: 1.1,
    defaultSize: { w: 740, h: 580 },
    minSize: { w: 400, h: 360 },
    home: { x: 3, y: 52 },
  },
  contact: {
    id: 'contact',
    title: 'Talk',
    hint: 'Say what you need — type it or speak it',
    icon: '/icons/talk.svg',
    iconScale: 1.12,
    defaultSize: { w: 560, h: 620 },
    minSize: { w: 340, h: 420 },
    home: { x: 3, y: 71 },
  },
  terminal: {
    id: 'terminal',
    title: 'Terminal',
    hint: 'Drive the whole site by keyboard',
    icon: '/icons/terminal.svg',
    iconScale: 1.0,
    defaultSize: { w: 760, h: 470 },
    minSize: { w: 380, h: 260 },
    home: { x: 90, y: 13 },
  },
  games: {
    id: 'games',
    title: 'Games',
    hint: 'Tetris and Minesweeper, because the wallpaper asked for it',
    icon: '/icons/games.svg',
    iconScale: 1.0,
    defaultSize: { w: 760, h: 700 },
    minSize: { w: 340, h: 420 },
    home: { x: 88, y: 52 },
  },
  legal: {
    id: 'legal',
    title: 'Legal',
    hint: 'Privacy, terms, cookies',
    icon: '/icons/legal.svg',
    iconScale: 1.0,
    defaultSize: { w: 680, h: 540 },
    minSize: { w: 360, h: 320 },
    home: { x: 90, y: 32 },
  },
};
