// Generates migrations/0002_seed.sql from src/data/projects.ts.
// Run: npx tsx scripts/seed-content.mts
// Re-runnable: uses INSERT OR REPLACE so re-seeding is idempotent.
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { projects } from '../src/data/projects';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

function literal(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

const lines = ['-- Auto-generated by scripts/seed-content.mts. Do not hand-edit.'];
for (const project of projects) {
  lines.push(
    `INSERT OR REPLACE INTO content (id, kind, data) VALUES (${literal(`project:${project.id}`)}, 'project', ${literal(JSON.stringify(project))});`,
  );
}

writeFileSync(resolve(root, 'migrations/0002_seed.sql'), `${lines.join('\n')}\n`);
console.log(`seeded ${projects.length} projects -> migrations/0002_seed.sql`);
